import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "rx-rust-py", "python"))
import rx_rust
from rx_rust import Observable

print("import ok")
print("min:", Observable.from_iter([3, 1, 2]).min().collect())
print("max:", Observable.from_iter([3, 1, 2]).max().collect())
print("mean:", Observable.from_iter([1, 2, 3, 4, 5]).mean().collect())
print("rolling_sum(3):", Observable.from_iter([1, 2, 3, 4, 5]).rolling_sum(3).collect())
print("cum_sum:", Observable.from_iter([1, 2, 3, 4]).cum_sum().collect())
print("distinct:", Observable.from_iter([1, 2, 1, 3, 2]).distinct().collect())
print("take_while < 4:", Observable.from_iter([1, 2, 3, 4, 5, 1]).take_while(lambda x: x < 4).collect())
print("skip_while < 4:", Observable.from_iter([1, 2, 3, 4, 5, 1]).skip_while(lambda x: x < 4).collect())
print("sort:", Observable.from_iter([3, 1, 2]).sort().collect())
print("top_k(2):", Observable.from_iter([5, 3, 1, 4, 2]).top_k(2).collect())
print("bottom_k(2):", Observable.from_iter([5, 3, 1, 4, 2]).bottom_k(2).collect())
print("switch_map iter:", Observable.from_iter([1, 2]).switch_map(lambda x: [x, x * 10]).collect())
print("combine_latest:", Observable.from_iter([1, 2, 3]).combine_latest([10, 20], lambda a, b: a + b).collect())
print("abs:", Observable.from_iter([-3, 0, 5]).abs().collect())
print("clamp:", Observable.from_iter([-10, 5, 100]).clamp(0, 10).collect())
print("explode lists:", Observable.from_iter([[1, 2], [3], [4, 5]]).explode().collect())
print("pipe min:", Observable.from_iter([3, 1, 2]).pipe(rx_rust.ops.min()).collect())
print("pipe distinct:", Observable.from_iter([1, 2, 1]).pipe(rx_rust.ops.distinct()).collect())
print("drop_none:", Observable.from_iter([1, None, 2]).drop_none().collect())
print("fill_none:", Observable.from_iter([1, None, 2]).fill_none(0).collect())
print("share:", Observable.from_iter([1, 2, 3]).share().collect())
print("distinct_until_changed:", Observable.from_iter([1, 1, 2, 2, 3, 1]).distinct_until_changed().collect())
print("arg_min:", Observable.from_iter([3, 1, 4, 1]).arg_min().collect())
print("arg_max:", Observable.from_iter([3, 1, 4, 1]).arg_max().collect())
print("n_unique:", Observable.from_iter([1, 2, 1, 3]).n_unique().collect())
print("any:", Observable.from_iter([1, 2, 3]).any(lambda x: x > 2).collect())
print("ignore_elements:", Observable.from_iter([1, 2, 3]).ignore_elements().collect())
print("element_at(0):", Observable.from_iter([10, 20, 30]).element_at(0).collect())
print("take_last(2):", Observable.from_iter([1, 2, 3, 4, 5]).take_last(2).collect())
print("skip_last(2):", Observable.from_iter([1, 2, 3, 4, 5]).skip_last(2).collect())
print("catch_error (no error):", Observable.from_iter([1, 2, 3]).catch_error(lambda e: Observable.of(99)).collect())
print("retry:", Observable.from_iter([1, 2, 3]).retry(2).collect())
print("retry_with_delay:", Observable.from_iter([1, 2, 3]).retry_with_delay(1, 0.01).collect())
print("all ok!")
